import { expect, test } from '@playwright/test';
import type { ARichTextElement } from '../../packages/web-component/src/index.js';

test('custom CSS parts and plain buttons preserve selection, undo and native forms', async ({ page }) => {
  await page.goto('/dist/browser/custom-toolbar.html');
  const editor = page.locator('#custom-editor');
  const surface = editor.locator('[part="editor"]');
  await expect(surface).toHaveCSS('border-top-width', '2px');
  await expect(surface).toHaveCSS('padding-top', '16px');
  await expect(surface).toHaveCSS('min-height', '192px');
  await surface.click();
  await surface.press('ControlOrMeta+a');
  await page.getByRole('button', { name: 'My bold button' }).click();
  expect(await editor.evaluate(node => (node as ARichTextElement).getHTML())).toBe('<p><strong>Style me with CSS parts.</strong></p>');
  await page.getByRole('button', { name: 'My quote button' }).focus();
  await page.keyboard.press('Enter');
  await expect(surface.locator('blockquote')).toHaveCSS('border-inline-start-width', '4px');
  await page.getByRole('button', { name: 'My undo button' }).click();
  await expect(surface.locator('blockquote')).toHaveCount(0);
  expect(await surface.locator('p').evaluate(node => Number.parseFloat(getComputedStyle(node).lineHeight))).toBeCloseTo(28.8, 3);
  await page.getByRole('button', { name: 'Save', exact: true }).click();
  await expect(page.locator('#custom-output')).toHaveText('<p><strong>Style me with CSS parts.</strong></p>');
  await page.addStyleTag({ content: 'a-rich-text::part(active-view-button) { font-weight: 900 }' });
  await page.getByRole('button', { name: 'HTML', exact: true }).click();
  await expect(page.getByRole('button', { name: 'HTML', exact: true })).toHaveCSS('font-weight', '900');
  await expect(page.getByRole('button', { name: 'My bold button' })).toHaveCount(0);
});

test('Vue v-model and toolbar slots preserve undo, Tailwind parts, locks and remounts', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/dist/browser/vue.html');
  const editor = page.locator('#vue-editor');
  const surface = editor.locator('[part="editor"]');
  await expect(surface).toHaveText('Hello from Vue');
  await expect(surface).toHaveCSS('border-top-width', '2px');
  await expect(surface).toHaveCSS('border-radius', '12px');
  const expectedColor = await page.evaluate(() => {
    const probe = document.createElement('span');
    probe.style.color = 'var(--color-indigo-500)';
    document.body.append(probe);
    const value = getComputedStyle(probe).color;
    probe.remove();
    return value;
  });
  await expect(surface).toHaveCSS('border-top-color', expectedColor);
  await surface.click();
  await surface.press('ControlOrMeta+a');
  await page.getByRole('button', { name: 'Custom bold', exact: true }).click();
  await expect(page.locator('#bound-value')).toHaveText('<p><strong>Hello from Vue</strong></p>');
  await page.getByRole('button', { name: 'Custom undo', exact: true }).click();
  await expect(page.locator('#bound-value')).toHaveText('<p>Hello from Vue</p>');
  await page.getByRole('button', { name: 'Load document', exact: true }).click();
  await expect(surface).toHaveText('Loaded externally');
  await page.getByRole('button', { name: 'Lock', exact: true }).click();
  await expect(surface).toHaveAttribute('aria-readonly', 'true');
  await expect(page.getByRole('button', { name: 'Custom bold', exact: true })).toHaveCount(0);
  await page.getByRole('button', { name: 'Unlock', exact: true }).click();
  await page.getByRole('button', { name: 'Unmount', exact: true }).click();
  await expect(editor).toHaveCount(0);
  await page.getByRole('button', { name: 'Mount', exact: true }).click();
  await expect(surface).toHaveText('Loaded externally');
  await surface.click();
  await surface.press('ControlOrMeta+a');
  await page.getByRole('button', { name: 'Custom italic', exact: true }).focus();
  await page.keyboard.press('Enter');
  await expect(page.locator('#bound-value')).toHaveText('<p><em>Loaded externally</em></p>');
  expect(errors).toEqual([]);
});
